/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomMenus: typeof import('./src/components/BottomMenus.vue')['default']
    ConfigMenus: typeof import('./src/components/ConfigMenus.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    LayColorPicker: typeof import('@layui/layui-vue')['LayColorPicker']
    Messages: typeof import('./src/components/Messages.vue')['default']
    RightMenus: typeof import('./src/components/RightMenus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
