// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BottomMenus: typeof import('./src/components/BottomMenus.vue')['default']
    ConfigMenus: typeof import('./src/components/ConfigMenus.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCheckbox: typeof import("element-plus/es")["ElCheckbox"]
    ElInput: typeof import('element-plus/es')['ElInput']
    LayColorPicker: typeof import('@layui/layui-vue')['LayColorPicker']
    RightMenus: typeof import('./src/components/RightMenus.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
